Repository threefreespirited/Jssconnect, pull requests merged in 2021-03, with the labels that each got.

#26 added issue and pr templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/proposal.md
  .github/pull_request_template.md
Labels: documentation, gssoc21

#40 Added automatic contributors in read me
  README.md
Labels: gssoc21, level0

#49 Added code for responsiveness of landing page issue-5
  .gitignore
  app.js
  public/css/header.css
  public/css/index.css
  views/index.css
  views/index.ejs
Labels: enhancement, gssoc21, level2

#48 Adding various security features, issue #45
  app.js
  package.json
Labels: gssoc21, level1

#59 Add Code of Conduct
  CODE_OF_CONDUCT.md
Labels: gssoc21, level1
